### ISSUE TITLE
Complete Lagon CLI commands

### ISSUE THREAD

**Issue by QuiiBz** [lagonapp/lagon#268]
Right now, `lagon` CLI only supports basic commands (https://docs.lagon.app/cli#usage). We should add support for every action possible in the dashboard:

- [x] Rename the `.lagon/config.json` to `.lagon/<file>.json` to allow having multiple functions inside the same directory (#274)
- [x] Rename `lagon undeploy <file>` to `lagon rm <file>` (#273)
- [x] Add `lagon undeploy <file> <deploymentId>` to undeploy a specific deployment (#300)
- [x] Add `lagon promote <file> <deploymentId>` to promote the specified deployment to production (#300)
- [x] Add `lagon ls <file>` to list deployments (#300)
- [x] Add `lagon link <file>` to link a file to a Function (https://github.com/lagonapp/lagon/pull/275)
- [ ] Save `public` directory to `<file>.json` config
